FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
ADD package.json /usr/src/app/package.json
RUN npm install

COPY . .
EXPOSE 4000

# start app
CMD ["npm", "start"]
